application: aestarter1
version: beta1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- appstats: off
- remote_api: off
- deferred: on

libraries:
- name: jinja2
  version: "latest"

inbound_services:
- warmup

handlers:
- url: /(robots\.txt|favicon\.ico|apple-touch-icon.*)
  static_files: static/root/\1
  upload: static/root/.*

- url: /static
  static_dir: static

# Adds aeadmin
- url: /admin/static
  static_dir: lib/dist/aeadmin/static

- url: /admin.*
  script: aeadmin.main.application

# This is listed separately because when using the '/_ah' prefix aecore
# authentication is not available, therefore we must use GAE authentication.
- url: /_ah/admin.*
  script: aeadmin.main.application
  login: admin

# Adds aeauth
- url: /auth/static
  static_dir: lib/dist/aeauth/static

- url: /auth.*
  script: aeauth.main.application

# Adds aeaccount
- url: /account/static
  static_dir: lib/dist/aeaccount/static

- url: /account.*
  script: aeaccount.main.application

# Adds aerest
- url: /api.*
  script: aerest.main.application

# All other urls are handled by the application.
- url: /.*
  script: main.application

error_handlers:
  - file: templates/error/default_error.html
  - error_code: over_quota
    file: templates/pages/over_quota.html
  - error_code: dos_api_denial
    file: templates/pages/dos_api_denial.html
  - error_code: timeout
    file: templates/pages/timout.html

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?index\.yaml
  - ^(.*/)?index\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?.*\.bak$
  #- ^(.*/)?.*\.coffee
  - ^(.*/)?.*\.sml
  #- ^(.*/)?.*\.hjs
  - static/styles/less/

